---
- name: Ensure dependencies are installed.
  package:
    name:
      - lsof
      - acl
      - sudo
    state: present

- name: Replace port
  command: sed -i 's/SOLR_PORT=8983/SOLR_PORT=7979/g' {{ solr_workspace }}/{{ solr_filename }}/bin/solr
  tags: ['skip_ansible_lint']

- name: Change user
  become_user: root
  command: chown -R {{ solr_user }}:{{ solr_group }} {{ solr_workspace }}
  tags: ['skip_ansible_lint']
# We add '-n' to Solr versions beyond 6.3.0 to prevent autostart on install.
- name: Run Solr installation script.
  command: >
    {{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh
    {{ solr_workspace }}/{{ solr_filename }}.tgz
    -i {{ solr_install_dir }}
    -d {{ solr_home }}
    -u {{ solr_user }}
    -s {{ solr_service_name }}
    -p {{ solr_port }}
    {{ (solr_version is version('6.3.0', '>=')) | ternary('-n','') }}
    {{ (solr_version is version('5.4.0', '>=')) | ternary('-f','') }}
    creates={{ solr_install_path }}/bin/solr
  register: solr_install_script_result

- name: Replace log file path
  command: sed -i 's/SOLR_LOGS_DIR="\/Application\/solr\/logs"/SOLR_LOGS_DIR="{{ solr_true_log_file_path }}"/g' {{ solr_config_file }} 
  tags: ['skip_ansible_lint']

# Workaround for bug https://github.com/ansible/ansible-modules-core/issues/915.
- name: Ensure solr is stopped (RHEL 7 workaround).
  command: service {{ solr_service_name }} stop
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] == '7'
    - solr_install_script_result.changed
  failed_when: false
  tags: ['skip_ansible_lint']

- name: Run systemd daemon_reload (RHEL 7 workaround).
  systemd:
    name: solr
    daemon_reload: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] == '7'
    - solr_install_script_result.changed
  tags: ['skip_ansible_lint']
