---

- name: Include version-specific variables for CentOS/RHEL.
  include_vars: "../templates/RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'

- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

- name: Ensure Java is installed.
  package:
    name: "{{ java_packages }}"
    state: present

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: ../templates/java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home